"""Bayesian GDP revision tools for Portugal."""

from .bayes import (
    BayesianLinearRegressionPosterior,
    NormalPosterior,
    fit_bayesian_linear_regression,
    normal_normal_update,
    summarize_samples,
)
from .data_sources import (
    DataDownloadError,
    WorldBankIndicator,
    cached_frame,
    default_cache_dir,
    fetch_eurostat_employment_rate,
    fetch_eurostat_national_accounts_employment,
    fetch_eurostat_national_accounts_population,
    fetch_eurostat_population,
    fetch_eurostat_pps_inputs,
    fetch_eurostat_series,
    fetch_oecd_employment_rate_by_birthplace,
    fetch_world_bank_indicator,
    fetch_world_bank_panel,
    get_known_value,
    load_known_observations,
    patch_manual_observation,
)
from .model import (
    GdpPosteriorResult,
    OutturnScore,
    PopulationPosteriorResult,
    backtest_gdp_model,
    capture_sensitivity_curve,
    check_extrapolation,
    estimate_gdp_posterior_samples,
    estimate_population_posterior_samples,
    estimate_pps_index_samples,
    pps_index_samples,
    score_against_outturn,
    simulate_unmeasured_output_samples,
)
from .reconciliation import (
    CorrectionVerdict,
    assess_correction_claim,
    compare_population_bases,
    derive_purchasing_power_parity,
    employment_absorbed_revision,
    employment_rate_excess_over_peers,
    implied_missing_workers,
    population_inside_index,
)

__all__ = [
    # bayes
    "BayesianLinearRegressionPosterior",
    "NormalPosterior",
    "fit_bayesian_linear_regression",
    "normal_normal_update",
    "summarize_samples",
    # data sources
    "DataDownloadError",
    "WorldBankIndicator",
    "cached_frame",
    "default_cache_dir",
    "fetch_eurostat_employment_rate",
    "fetch_eurostat_national_accounts_employment",
    "fetch_eurostat_national_accounts_population",
    "fetch_eurostat_population",
    "fetch_eurostat_pps_inputs",
    "fetch_eurostat_series",
    "fetch_oecd_employment_rate_by_birthplace",
    "fetch_world_bank_indicator",
    "fetch_world_bank_panel",
    "get_known_value",
    "load_known_observations",
    "patch_manual_observation",
    # model
    "GdpPosteriorResult",
    "OutturnScore",
    "PopulationPosteriorResult",
    "backtest_gdp_model",
    "capture_sensitivity_curve",
    "check_extrapolation",
    "estimate_gdp_posterior_samples",
    "estimate_population_posterior_samples",
    "estimate_pps_index_samples",
    "pps_index_samples",
    "score_against_outturn",
    "simulate_unmeasured_output_samples",
    # reconciliation
    "CorrectionVerdict",
    "assess_correction_claim",
    "compare_population_bases",
    "derive_purchasing_power_parity",
    "employment_absorbed_revision",
    "employment_rate_excess_over_peers",
    "implied_missing_workers",
    "population_inside_index",
]
